# Generated by Django 3.0.4 on 2020-04-23 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='myOrders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, size=None),
        ),
    ]
