# Generated by Django 3.0.4 on 2020-04-23 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200423_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='myOrders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
