# Generated by Django 3.0.4 on 2020-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200423_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
