# Generated by Django 3.0.4 on 2020-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_user'),
        ('authorization', '0006_auto_20200424_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='liked_products', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='myOrders',
            field=models.ManyToManyField(related_name='bought_products', to='api.Product'),
        ),
    ]
